# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import incident_pb2 as incident__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in incident_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class IncidentServiceStub(object):
    """── Services ───────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListIncidents = channel.unary_unary(
                '/incident.v1.IncidentService/ListIncidents',
                request_serializer=incident__pb2.ListIncidentsRequest.SerializeToString,
                response_deserializer=incident__pb2.ListIncidentsResponse.FromString,
                _registered_method=True)
        self.GetIncident = channel.unary_unary(
                '/incident.v1.IncidentService/GetIncident',
                request_serializer=incident__pb2.GetIncidentRequest.SerializeToString,
                response_deserializer=incident__pb2.GetIncidentResponse.FromString,
                _registered_method=True)
        self.StreamIncidents = channel.unary_stream(
                '/incident.v1.IncidentService/StreamIncidents',
                request_serializer=incident__pb2.StreamIncidentsRequest.SerializeToString,
                response_deserializer=incident__pb2.Incident.FromString,
                _registered_method=True)


class IncidentServiceServicer(object):
    """── Services ───────────────────────────────────────────────────────────────

    """

    def ListIncidents(self, request, context):
        """list all incidents, newest first
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncident(self, request, context):
        """get a single incident with full RCA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIncidents(self, request, context):
        """server-streaming: push new/updated incidents to connected clients
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IncidentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListIncidents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIncidents,
                    request_deserializer=incident__pb2.ListIncidentsRequest.FromString,
                    response_serializer=incident__pb2.ListIncidentsResponse.SerializeToString,
            ),
            'GetIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncident,
                    request_deserializer=incident__pb2.GetIncidentRequest.FromString,
                    response_serializer=incident__pb2.GetIncidentResponse.SerializeToString,
            ),
            'StreamIncidents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamIncidents,
                    request_deserializer=incident__pb2.StreamIncidentsRequest.FromString,
                    response_serializer=incident__pb2.Incident.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'incident.v1.IncidentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('incident.v1.IncidentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IncidentService(object):
    """── Services ───────────────────────────────────────────────────────────────

    """

    @staticmethod
    def ListIncidents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.v1.IncidentService/ListIncidents',
            incident__pb2.ListIncidentsRequest.SerializeToString,
            incident__pb2.ListIncidentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.v1.IncidentService/GetIncident',
            incident__pb2.GetIncidentRequest.SerializeToString,
            incident__pb2.GetIncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamIncidents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/incident.v1.IncidentService/StreamIncidents',
            incident__pb2.StreamIncidentsRequest.SerializeToString,
            incident__pb2.Incident.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AlertServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestEvent = channel.unary_unary(
                '/incident.v1.AlertService/IngestEvent',
                request_serializer=incident__pb2.IngestEventRequest.SerializeToString,
                response_deserializer=incident__pb2.IngestEventResponse.FromString,
                _registered_method=True)


class AlertServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestEvent(self, request, context):
        """ingest a log event or alert from external sources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEvent,
                    request_deserializer=incident__pb2.IngestEventRequest.FromString,
                    response_serializer=incident__pb2.IngestEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'incident.v1.AlertService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('incident.v1.AlertService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlertService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.v1.AlertService/IngestEvent',
            incident__pb2.IngestEventRequest.SerializeToString,
            incident__pb2.IngestEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnalysisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerAnalysis = channel.unary_unary(
                '/incident.v1.AnalysisService/TriggerAnalysis',
                request_serializer=incident__pb2.GetIncidentRequest.SerializeToString,
                response_deserializer=incident__pb2.RootCauseAnalysis.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerAnalysis(self, request, context):
        """manually trigger RCA re-generation for an incident
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerAnalysis,
                    request_deserializer=incident__pb2.GetIncidentRequest.FromString,
                    response_serializer=incident__pb2.RootCauseAnalysis.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'incident.v1.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('incident.v1.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/incident.v1.AnalysisService/TriggerAnalysis',
            incident__pb2.GetIncidentRequest.SerializeToString,
            incident__pb2.RootCauseAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
